### PR TITLE
feat: type definitions

### PR DESCRIPTION
**Pull request by Sayan751**
This PR adds the type definitions to the package. This is beneficial when this package is used in TypeScript projects.

And thank you for this awesome package :)

### CODE REVIEW

**Comment by papakai** [comment]
@Sayan751 your PR is really welcome. Thanks so much!

**Comment by Sayan751** [comment]
@papakai Thank you for the ninja-fast publish :)

**Comment by papakai** [comment]
I just reworded the commit message and pressed the `Merge` button the rest is completely automated. :-) I have to say thank you for the contribution - highly appreciated!

**Comment by Sayan751** [comment]
My pleasure :)

**Pull request merged**
