### PR TITLE
feat(unicode): update to v13.0.0

### PR DESCRIPTION
**Pull request by KosGrillis**
Using the included `build-unicode-tables` Python script, this PR adds Unicode 13.0.0 support to `idna-uts46`. While attempting to run the Python script, I encountered a few errors which required me to also make changes to the script itself, these are detailed below.

### Polyfill `unichr` for MacOS narrow Python build

The built-in `unichr` function failed with a `ValueError` when first attempting to run the script:
```python
ValueError: unichr() arg not in range(0x10000) (narrow Python build)
```

To fix this, I added a polyfill function `unichar`, which defaults to using `unichr` but then switches to a workaround when a `ValueError` is thrown

### Update "special case" assertion constraints for the Unicode 13 tables

Lines 147 - 151 of `build-unicode-tables` deals with some sort of special case in the Unicode mapping that relies on hardcoded hexadecimal code points to work. When attempting to run the script for Unicode 13, the assertion failed. This required some guesswork to figure out, but I figured that the difference in the mapping table in Unicode 13 was the cause of the failure.

Note below the relevant parts of the [mapping table for Unicode 12](https://www.unicode.org/Public/idna/13.0.0/IdnaMappingTable.txt) (right at the bottom of the file):
image (9)

Compare this with the relevant parts of the [mapping table for Unicode 13](https://www.unicode.org/Public/idna/13.0.0/IdnaMappingTable.txt):
image (10)

You'll notice actually that the assertion constraints didn't change, rather the disallowed code points that were used as the special case were made **valid** in Unicode 13. Hence, I updated the `specialCase` variable to start at the next disallowed codepoint `0x3134B`. I'm not 100% sure if this is the correct solution, but after making the change, the script succeeded and the output looked about similar to the previous Unicode tables

### CODE REVIEW

**Comment by papakai** [comment]
Hi @KosGrillis,

I am really thankful for your contribution. I am too busy to dive into such things on my own. Next big chapter here is to get that build script ported to Python 3 or migrated to Node.js which is my favourite. I covered the whole build and release process already with Javascript and this module itself is Javascript, but the build part is written in Python? That's giving me headaches :-)

Regarding your PR - I see that you marked it as WIP, still some feedback in advance:
* ensure your commit messages follow a semantic format. You can reword your commits by
  ```bash
  git rebase -i HEAD~2
  ```
  Now mark/set all of the commits to action "r" (reword) by replacing "pick" with "r" and save. You'll then be forwarded to the rewording step where you can change the commit messages. NOTE: use the latest git-scm version, older git versions may break with interactive rebasing. Finally a force push.
```bash
git push -f
```
* pep8check failed, simply run `/.scripts/pep8fix.sh` and commit the style changes
* I also suggest to squash all your commits into one as final step by
  ```bash
  # replace "#" below with the number of commits in your PR
  git rebase -i HEAD~#
  ```
  Set the commits you want to squash or fixup to "s" (squash) instead of pick. Leave your first commit of your PR set to "pick". In that way all your other commits will be squashed into your first commit. Finally proceed with a force push
  `git push -f`
  You may then again want to reword your single commit message - so just follow step 1 again.

HTH, otherwise let me know.

**Comment by KosGrillis** [comment]
@papakai 

Thanks for your help! I've gone ahead and linted the Python script and squashed my commits. Also confirm that tests are passing. This should now be ready for your review!

**Comment by papakai** [comment]
@KosGrillis thanks for the contribution again and sorry for the delay - busy days.

**Pull request merged**
